version: '3.9'
services:
  jupyternotebook:
    image: ghcr.io/yanorei32/uthree-ml-image:latest@sha256:e6d2a4ce1557fb3dbe89bfbe5279c052d55b1ceeb780ad27d5fd2e24ec3d51f3
    hostname: jupyternotebook
    container_name: uthreemlrulia__jupyternotebook

    restart: unless-stopped

    init: true

    environment:
      SHELL: "/bin/bash"

    volumes:
      - type: volume
        source: workdir
        target: /root

    expose:
      - 8080

    networks:
      - jupyternotebook_nginx
      - jupyternotebook_internet

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m

  nginx:
    image: nginx:1.23.1
    hostname: nginx
    container_name: uthreemlrulia__nginx

    environment:
      HTPASSWD: ${HTPASSWD}

    restart: unless-stopped

    depends_on:
      - jupyternotebook

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: ./command.sh
        target: /command.sh
        read_only: true

    command: /command.sh

    networks:
      - nginx_cloudflared
      - jupyternotebook_nginx

    expose:
      - 80

    deploy:
      resources:
        limits:
          memory: 256m

    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m

  cloudflared:
    image: cloudflare/cloudflared:2022.7.1
    hostname: cloudflared
    container_name: uthreemlrulia__cloudflared

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_URL: http://nginx:80
      TUNNEL_HOSTNAME: jupyter.yr32.net
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel
    user: root

    depends_on:
      - nginx

    restart: unless-stopped

    volumes:
      - type: bind
        source: /etc/cloudflared/cert.pem
        target: /etc/cloudflared/cert.pem
        read_only: true

    networks:
      nginx_cloudflared:
      cloudflared_internet:
      prometheus__cloudflared:
        aliases:
          - uthreemlrulia__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m

volumes:
  workdir:
    name: uthreemlrulia__workdir

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  jupyternotebook_nginx:
    name: uthreemlrulia__jupyternotebook_nginx
    internal: true

  nginx_cloudflared:
    name: uthreemlrulia__nginx_cloudflared
    internal: true

  jupyternotebook_internet:
    name: uthreemlrulia__jupyternotebook_internet

  cloudflared_internet:
    name: uthreemlrulia__cloudflared_internet
