version: '3.9'
services:
  squid:
    image: datadog/squid@sha256:f7d19d5e3f4163771291d91de393ce667f2327a3e080c39b9b7ea9e19f91488f
    hostname: squid
    container_name: ruliaml__squid 
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./squid.conf
        target: /etc/squid/squid.conf
        read_only: true

    networks:
      - default
      - outband

    deploy:
      resources:
        limits:
          memory: 256m

  jupyternotebook:
    image: ghcr.io/yanorei32/uthree-ml-image:0.5.3
    hostname: jupyternotebook
    container_name: ruliaml__jupyternotebook
    restart: unless-stopped
    init: true

    environment:
      SHELL: "/bin/bash"
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128

    volumes:
      - type: volume
        source: workdir
        target: /root

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2022.8.4-amd64@sha256:52b8a267e4f262846e9eb24eb25e9a0cdd216d2ae489522c27bc25e01772f93e
    hostname: cloudflared
    container_name: ruliaml__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - ruliaml__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  workdir:
    name: ruliaml__workdir

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: ruliaml__default
    internal: true

  outband:
    name: ruliaml__outband
