version: '3.9'
services:
  jupyternotebook:
    image: ghcr.io/yanorei32/uthree-ml-image:latest@sha256:10bb24ef15b2c85fe727dae2dbe3ea07d721670bed2ec17f573c55e4f2744411
    hostname: jupyternotebook
    container_name: ruliaml__jupyternotebook

    restart: unless-stopped

    init: true

    environment:
      SHELL: "/bin/bash"

    volumes:
      - type: volume
        source: workdir
        target: /root

    networks:
      - jupyternotebook_nginx
      - jupyternotebook_internet

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  nginx:
    image: nginx:1.23.1
    hostname: nginx
    container_name: ruliaml__nginx

    environment:
      HTPASSWD: ${HTPASSWD}

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: ./command.sh
        target: /command.sh
        read_only: true

    command: /command.sh

    networks:
      - nginx_cloudflared
      - jupyternotebook_nginx

    deploy:
      resources:
        limits:
          memory: 128m

  cloudflared:
    image: cloudflare/cloudflared:2022.8.0
    hostname: cloudflared
    container_name: ruliaml__cloudflared

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_URL: http://nginx:80
      TUNNEL_HOSTNAME: ruliaml.yr32.net
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel
    user: root

    restart: unless-stopped

    volumes:
      - type: bind
        source: /etc/cloudflared/cert.pem
        target: /etc/cloudflared/cert.pem
        read_only: true

    networks:
      nginx_cloudflared:
      cloudflared_internet:
      prometheus__cloudflared:
        aliases:
          - ruliaml__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  workdir:
    name: ruliaml__workdir

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  jupyternotebook_nginx:
    name: ruliaml__jupyternotebook_nginx
    internal: true

  nginx_cloudflared:
    name: ruliaml__nginx_cloudflared
    internal: true

  jupyternotebook_internet:
    name: ruliaml__jupyternotebook_internet

  cloudflared_internet:
    name: ruliaml__cloudflared_internet
