version: '3.9'
services:
  squid:
    image: ubuntu/squid:5.2-22.04_beta@sha256:6fadf85fa22988eedbd503cf42947cf3aa285d6d9a72c0a45535f76d9b19d2dd
    hostname: squid
    container_name: ruliaml__squid 
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./squid.conf
        target: /etc/squid/squid.conf
        read_only: true

    networks:
      - default
      - outband

    deploy:
      resources:
        limits:
          memory: 256m

  jupyternotebook:
    image: ghcr.io/yanorei32/uthree-ml-image:0.6.0
    hostname: jupyternotebook
    container_name: ruliaml__jupyternotebook
    restart: unless-stopped
    init: true

    environment:
      SHELL: "/bin/bash"
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128

    volumes:
      - type: volume
        source: workdir
        target: /root

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2023.4.0-amd64@sha256:60cc2e88eb74cc38a36fdc9a9d9a04de34e1d55e43563e94908a7d6128a52210
    hostname: cloudflared
    container_name: ruliaml__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - ruliaml__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  workdir:
    name: ruliaml__workdir

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: ruliaml__default
    internal: true

  outband:
    name: ruliaml__outband
